spring:
  application:
    name: challengeLab
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    url: jdbc:h2:./challengelab;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
application:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 900000
      name: jwt-cookie
    refresh-token:
      expiration: 1296000000
      name: refresh