spring:
  application:
    name: challengeLab
  profiles:
    active:
      - dev
application:
  security:
    jwt:
      secret: ${SECRET_KEY}
      expiration: 900000
      name: jwt-cookie
    refresh-token:
      expiration: 1296000000
      name: refresh
springdoc:
  swagger-ui:
    tags-sorter: alpha